apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-server-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-server-label
  template:
    metadata:
      labels:
        app: my-server-label
    spec:
      containers:
      - name: my-server
        image: kicbase/echo-server:1.0
---
kind: Service
apiVersion: v1
metadata:
  name: my-server-service
spec:
  selector:
    app: my-server-label
  type: NodePort
  ports:
    - port: 8080
