apiVersion: v1
kind: Service
metadata:
  name: odoo-postgres
  labels:
    app: odoo
spec:
  ports:
    - port: 5432
  selector:
    app: odoo
    tier: postgres
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: odoo-postgres
  labels:
    app: odoo
spec:
  selector:
    matchLabels:
      app: odoo
      tier: postgres
  template:
    metadata:
      labels:
        app: odoo
        tier: postgres
    spec:
      containers:
      - image: postgres:15
        name: postgres
        env:
        - name: POSTGRES_USER
          value: odoo
        - name: POSTGRES_DB
          value: postgres
        - name: POSTGRES_PASSWORD
          value: myodoo
