apiVersion: v1
kind: Service
metadata:
  name: <myApp>
  labels:
    app: <myApp>
spec:
  type: NodePort
  ports:
    - port: 80
  selector:
    app: <myApp>
    tier: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: <myApp>
  labels:
    app: <myApp>
spec:
  selector:
    matchLabels:
      app: <myApp>
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: <myApp>
        tier: frontend
    spec:
      containers:
      - image: <myApp>:<version/tag>
        name: <myApp>
        env:
        - name: <myEnv>
          value: <myValue>
        ports:
        - containerPort: <MyPort exemple 80>
          name: <myApp>
