apiVersion: v1
kind: Service
metadata:
  name: metadatabase
  labels:
    app: metadatabase
spec:
  type: NodePort
  ports:
    - port: 3000
  selector:
    app: metadatabase
    tier: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metadatabase
  labels:
    app: metadatabase
spec:
  selector:
    matchLabels:
      app: metadatabase
      tier: frontend
  template:
    metadata:
      labels:
        app: metadatabase
        tier: frontend
    spec:
      containers:
      - image: metabase/metabase
        name: metadatabase
        env:
        - name: MB_DB_TYPE
          value: postgres
        - name: MB_DB_DBNAME
          value: metabaseappdb
        - name: MB_DB_PORT
          value: "5432"
        - name: MB_DB_USER
          value: metabase
        - name: MB_DB_PASS
          value: mysecretpassword
        - name: MB_DB_HOST
          value: metadatabase-postgres
