apiVersion: v1
kind: Service
metadata:
  name: metadatabase-postgres
  labels:
    app: metadatabase
spec:
  ports:
    - port: 5432
  selector:
    app: metadatabase
    tier: postgres
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metadatabase-postgres
  labels:
    app: metadatabase
spec:
  selector:
    matchLabels:
      app: metadatabase
      tier: postgres
  template:
    metadata:
      labels:
        app: metadatabase
        tier: postgres
    spec:
      containers:
      - image: postgres
        name: postgres
        env:
        - name: POSTGRES_USER
          value: metabase
        - name: POSTGRES_DB
          value: metabaseappdb
        - name: POSTGRES_PASSWORD
          value: mysecretpassword
