apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app-label
  template:
    metadata:
      labels:
        app: my-app-label
    spec:
      containers:
        - name: my-container
          image: fredericbui/demoenv
          env:
            - name: MY_ENV
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: myenv
---
kind: Service
apiVersion: v1
metadata:
  name: my-service
spec:
  selector:
    app: my-app-label
  type: NodePort
  ports:
    - port: 80